
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pg_network
    container_name: postgres
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    depends_on:
      - postgres
    networks:
      - pg_network
    container_name: pgadmin
  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    environment:
      - MINIO_ROOT_USER=minio_user
      - MINIO_ROOT_PASSWORD=minio_password
      - MINIO_ADDRESS=:9000
      - MINIO_CONSOLE_ADDRESS:9001
    ports:
      - 9000:9000
      - 9001:9001
    volumes: 
      - ./data:/data
    command: minio server /data
    container_name: minio

networks:
  pg_network:
    driver: bridge

